// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Plataforma.Infrastructure.Persistence;

#nullable disable

namespace Plataforma.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260901130953_AgregarSolicitudesViabilidadAmbiental")]
    partial class AgregarSolicitudesViabilidadAmbiental
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Plataforma.Domain.Leads.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset?>("NotificacionComercialEnviadaEn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("notificacion_comercial_enviada_en");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("origen");

                    b.Property<Guid?>("PropiedadDeInteresId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("propiedad_de_interes_id");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("Origen");

                    b.ToTable("leads", (string)null);
                });

            modelBuilder.Entity("Plataforma.Domain.Propiedades.Propiedad", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("estado");

                    b.Property<string>("TipoInmueble")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("tipo_inmueble");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("TipoInmueble");

                    b.ToTable("propiedades", (string)null);
                });

            modelBuilder.Entity("Plataforma.Domain.ViabilidadAmbiental.SolicitudViabilidadAmbiental", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset?>("PagoConfirmadoEn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("pago_confirmado_en");

                    b.Property<Guid?>("PropiedadId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("propiedad_id");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.ToTable("solicitudes_viabilidad_ambiental", (string)null);
                });

            modelBuilder.Entity("Plataforma.Domain.Leads.Lead", b =>
                {
                    b.OwnsOne("Plataforma.Domain.Leads.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("LeadId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("nvarchar(254)")
                                .HasColumnName("email");

                            b1.HasKey("LeadId");

                            b1.ToTable("leads");

                            b1.WithOwner()
                                .HasForeignKey("LeadId");
                        });

                    b.OwnsOne("Plataforma.Domain.Leads.ValueObjects.Telefono", "Telefono", b1 =>
                        {
                            b1.Property<Guid>("LeadId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Indicativo")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("nvarchar(5)")
                                .HasColumnName("telefono_indicativo");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("nvarchar(15)")
                                .HasColumnName("telefono_numero");

                            b1.HasKey("LeadId");

                            b1.ToTable("leads");

                            b1.WithOwner()
                                .HasForeignKey("LeadId");
                        });

                    b.OwnsOne("Plataforma.Domain.Leads.ValueObjects.EstimacionCosto", "ResultadoCalculadora", b1 =>
                        {
                            b1.Property<Guid>("LeadId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("CalculadoEn")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("estimacion_calculada_en");

                            b1.HasKey("LeadId");

                            b1.ToTable("leads");

                            b1.WithOwner()
                                .HasForeignKey("LeadId");

                            b1.OwnsOne("Plataforma.Domain.Leads.ValueObjects.DatosCalculoObra", "DatosEntrada", b2 =>
                                {
                                    b2.Property<Guid>("EstimacionCostoLeadId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("AreaConstruccionM2")
                                        .HasColumnType("numeric(12,2)")
                                        .HasColumnName("calculo_area_construccion_m2");

                                    b2.Property<string>("Municipio")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)")
                                        .HasColumnName("calculo_municipio");

                                    b2.Property<string>("TipoAcabado")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("nvarchar(20)")
                                        .HasColumnName("calculo_tipo_acabado");

                                    b2.Property<string>("TipoProyecto")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("nvarchar(20)")
                                        .HasColumnName("calculo_tipo_proyecto");

                                    b2.HasKey("EstimacionCostoLeadId");

                                    b2.ToTable("leads");

                                    b2.WithOwner()
                                        .HasForeignKey("EstimacionCostoLeadId");
                                });

                            b1.OwnsOne("Plataforma.Domain.SharedKernel.Dinero", "MontoMaximo", b2 =>
                                {
                                    b2.Property<Guid>("EstimacionCostoLeadId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Moneda")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("nvarchar(3)")
                                        .HasColumnName("estimacion_maxima_moneda");

                                    b2.Property<decimal>("Monto")
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("estimacion_maxima_monto");

                                    b2.HasKey("EstimacionCostoLeadId");

                                    b2.ToTable("leads");

                                    b2.WithOwner()
                                        .HasForeignKey("EstimacionCostoLeadId");
                                });

                            b1.OwnsOne("Plataforma.Domain.SharedKernel.Dinero", "MontoMinimo", b2 =>
                                {
                                    b2.Property<Guid>("EstimacionCostoLeadId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Moneda")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("nvarchar(3)")
                                        .HasColumnName("estimacion_minima_moneda");

                                    b2.Property<decimal>("Monto")
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("estimacion_minima_monto");

                                    b2.HasKey("EstimacionCostoLeadId");

                                    b2.ToTable("leads");

                                    b2.WithOwner()
                                        .HasForeignKey("EstimacionCostoLeadId");
                                });

                            b1.OwnsMany("Plataforma.Domain.Leads.ValueObjects.DesgloseItem", "Desglose", b2 =>
                                {
                                    b2.Property<int>("id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("id"));

                                    b2.Property<string>("Categoria")
                                        .IsRequired()
                                        .HasMaxLength(60)
                                        .HasColumnType("nvarchar(60)")
                                        .HasColumnName("categoria");

                                    b2.Property<Guid>("lead_id")
                                        .HasColumnType("uniqueidentifier");

                                    b2.HasKey("id");

                                    b2.HasIndex("lead_id");

                                    b2.ToTable("lead_estimacion_desglose", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("lead_id");

                                    b2.OwnsOne("Plataforma.Domain.SharedKernel.Dinero", "Monto", b3 =>
                                        {
                                            b3.Property<int>("DesgloseItemid")
                                                .HasColumnType("int");

                                            b3.Property<string>("Moneda")
                                                .IsRequired()
                                                .HasMaxLength(3)
                                                .HasColumnType("nvarchar(3)")
                                                .HasColumnName("moneda");

                                            b3.Property<decimal>("Monto")
                                                .HasColumnType("numeric(18,2)")
                                                .HasColumnName("monto");

                                            b3.HasKey("DesgloseItemid");

                                            b3.ToTable("lead_estimacion_desglose");

                                            b3.WithOwner()
                                                .HasForeignKey("DesgloseItemid");
                                        });

                                    b2.Navigation("Monto")
                                        .IsRequired();
                                });

                            b1.Navigation("DatosEntrada")
                                .IsRequired();

                            b1.Navigation("Desglose");

                            b1.Navigation("MontoMaximo")
                                .IsRequired();

                            b1.Navigation("MontoMinimo")
                                .IsRequired();
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("ResultadoCalculadora");

                    b.Navigation("Telefono")
                        .IsRequired();
                });

            modelBuilder.Entity("Plataforma.Domain.Propiedades.Propiedad", b =>
                {
                    b.OwnsOne("Plataforma.Domain.Propiedades.ValueObjects.Area", "AreaConstruida", b1 =>
                        {
                            b1.Property<Guid>("PropiedadId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("UnidadMedida")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("area_construida_unidad");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("area_construida_valor");

                            b1.HasKey("PropiedadId");

                            b1.ToTable("propiedades");

                            b1.WithOwner()
                                .HasForeignKey("PropiedadId");
                        });

                    b.OwnsOne("Plataforma.Domain.Propiedades.ValueObjects.Area", "AreaTerreno", b1 =>
                        {
                            b1.Property<Guid>("PropiedadId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("UnidadMedida")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("area_terreno_unidad");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("area_terreno_valor");

                            b1.HasKey("PropiedadId");

                            b1.ToTable("propiedades");

                            b1.WithOwner()
                                .HasForeignKey("PropiedadId");
                        });

                    b.OwnsOne("Plataforma.Domain.SharedKernel.Dinero", "Precio", b1 =>
                        {
                            b1.Property<Guid>("PropiedadId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("precio_moneda");

                            b1.Property<decimal>("Monto")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("precio_monto");

                            b1.HasKey("PropiedadId");

                            b1.ToTable("propiedades");

                            b1.WithOwner()
                                .HasForeignKey("PropiedadId");
                        });

                    b.OwnsOne("Plataforma.Domain.Propiedades.ValueObjects.CaracteristicasTopograficas", "CaracteristicasTopograficas", b1 =>
                        {
                            b1.Property<Guid>("PropiedadId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal?>("NivelFreaticoMetros")
                                .HasColumnType("numeric(6,2)")
                                .HasColumnName("nivel_freatico_metros");

                            b1.Property<decimal>("PendientePorcentaje")
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("pendiente_porcentaje");

                            b1.Property<string>("TipoSuelo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("tipo_suelo");

                            b1.Property<string>("Topografia")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("topografia");

                            b1.HasKey("PropiedadId");

                            b1.ToTable("propiedades");

                            b1.WithOwner()
                                .HasForeignKey("PropiedadId");
                        });

                    b.OwnsOne("Plataforma.Domain.Propiedades.ValueObjects.Ubicacion", "Ubicacion", b1 =>
                        {
                            b1.Property<Guid>("PropiedadId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Departamento")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("departamento");

                            b1.Property<string>("Direccion")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("direccion");

                            b1.Property<string>("Municipio")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("municipio");

                            b1.HasKey("PropiedadId");

                            b1.ToTable("propiedades");

                            b1.WithOwner()
                                .HasForeignKey("PropiedadId");

                            b1.OwnsOne("Plataforma.Domain.Propiedades.ValueObjects.Coordenadas", "Coordenadas", b2 =>
                                {
                                    b2.Property<Guid>("UbicacionPropiedadId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Latitud")
                                        .HasColumnType("numeric(9,6)")
                                        .HasColumnName("latitud");

                                    b2.Property<decimal>("Longitud")
                                        .HasColumnType("numeric(9,6)")
                                        .HasColumnName("longitud");

                                    b2.HasKey("UbicacionPropiedadId");

                                    b2.ToTable("propiedades");

                                    b2.WithOwner()
                                        .HasForeignKey("UbicacionPropiedadId");
                                });

                            b1.Navigation("Coordenadas");
                        });

                    b.OwnsMany("Plataforma.Domain.Propiedades.ArchivoMultimedia", "Multimedia", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<int>("Orden")
                                .HasColumnType("int")
                                .HasColumnName("orden");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("tipo");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("url");

                            b1.Property<Guid>("propiedad_id")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("propiedad_id");

                            b1.ToTable("propiedad_multimedia", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("propiedad_id");
                        });

                    b.OwnsMany("Plataforma.Domain.Propiedades.ValueObjects.RetiroAmbiental", "RetirosAmbientales", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("id"));

                            b1.Property<decimal>("DistanciaMinimaMetros")
                                .HasColumnType("numeric(8,2)")
                                .HasColumnName("distancia_minima_metros");

                            b1.Property<string>("NormativaAplicable")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("normativa_aplicable");

                            b1.Property<string>("TipoFuente")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("tipo_fuente");

                            b1.Property<Guid>("propiedad_id")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("id");

                            b1.HasIndex("propiedad_id");

                            b1.ToTable("propiedad_retiros_ambientales", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("propiedad_id");
                        });

                    b.Navigation("AreaConstruida");

                    b.Navigation("AreaTerreno")
                        .IsRequired();

                    b.Navigation("CaracteristicasTopograficas")
                        .IsRequired();

                    b.Navigation("Multimedia");

                    b.Navigation("Precio")
                        .IsRequired();

                    b.Navigation("RetirosAmbientales");

                    b.Navigation("Ubicacion")
                        .IsRequired();
                });

            modelBuilder.Entity("Plataforma.Domain.ViabilidadAmbiental.SolicitudViabilidadAmbiental", b =>
                {
                    b.OwnsOne("Plataforma.Domain.SharedKernel.Dinero", "Monto", b1 =>
                        {
                            b1.Property<Guid>("SolicitudViabilidadAmbientalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("moneda");

                            b1.Property<decimal>("Monto")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("monto");

                            b1.HasKey("SolicitudViabilidadAmbientalId");

                            b1.ToTable("solicitudes_viabilidad_ambiental");

                            b1.WithOwner()
                                .HasForeignKey("SolicitudViabilidadAmbientalId");
                        });

                    b.OwnsOne("Plataforma.Domain.ViabilidadAmbiental.ValueObjects.DatosSolicitante", "Solicitante", b1 =>
                        {
                            b1.Property<Guid>("SolicitudViabilidadAmbientalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("solicitante_nombre");

                            b1.HasKey("SolicitudViabilidadAmbientalId");

                            b1.ToTable("solicitudes_viabilidad_ambiental");

                            b1.WithOwner()
                                .HasForeignKey("SolicitudViabilidadAmbientalId");

                            b1.OwnsOne("Plataforma.Domain.Leads.ValueObjects.Email", "Email", b2 =>
                                {
                                    b2.Property<Guid>("DatosSolicitanteSolicitudViabilidadAmbientalId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Valor")
                                        .IsRequired()
                                        .HasMaxLength(254)
                                        .HasColumnType("nvarchar(254)")
                                        .HasColumnName("solicitante_email");

                                    b2.HasKey("DatosSolicitanteSolicitudViabilidadAmbientalId");

                                    b2.ToTable("solicitudes_viabilidad_ambiental");

                                    b2.WithOwner()
                                        .HasForeignKey("DatosSolicitanteSolicitudViabilidadAmbientalId");
                                });

                            b1.OwnsOne("Plataforma.Domain.Leads.ValueObjects.Telefono", "Telefono", b2 =>
                                {
                                    b2.Property<Guid>("DatosSolicitanteSolicitudViabilidadAmbientalId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Indicativo")
                                        .IsRequired()
                                        .HasMaxLength(5)
                                        .HasColumnType("nvarchar(5)")
                                        .HasColumnName("solicitante_telefono_indicativo");

                                    b2.Property<string>("Numero")
                                        .IsRequired()
                                        .HasMaxLength(15)
                                        .HasColumnType("nvarchar(15)")
                                        .HasColumnName("solicitante_telefono_numero");

                                    b2.HasKey("DatosSolicitanteSolicitudViabilidadAmbientalId");

                                    b2.ToTable("solicitudes_viabilidad_ambiental");

                                    b2.WithOwner()
                                        .HasForeignKey("DatosSolicitanteSolicitudViabilidadAmbientalId");
                                });

                            b1.Navigation("Email")
                                .IsRequired();

                            b1.Navigation("Telefono")
                                .IsRequired();
                        });

                    b.OwnsOne("Plataforma.Domain.ViabilidadAmbiental.ValueObjects.UbicacionLote", "UbicacionLote", b1 =>
                        {
                            b1.Property<Guid>("SolicitudViabilidadAmbientalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Departamento")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("lote_departamento");

                            b1.Property<string>("DireccionReferencia")
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)")
                                .HasColumnName("lote_direccion_referencia");

                            b1.Property<string>("Municipio")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("lote_municipio");

                            b1.HasKey("SolicitudViabilidadAmbientalId");

                            b1.ToTable("solicitudes_viabilidad_ambiental");

                            b1.WithOwner()
                                .HasForeignKey("SolicitudViabilidadAmbientalId");
                        });

                    b.Navigation("Monto")
                        .IsRequired();

                    b.Navigation("Solicitante")
                        .IsRequired();

                    b.Navigation("UbicacionLote");
                });
#pragma warning restore 612, 618
        }
    }
}
